version: '3.8'

services:
  db:
    image: postgres:16
    container_name: medical_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  superset:
    build: ./superset
    container_name: superset_bi
    depends_on:
      - db
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: "${SUPERSET_SECRET_KEY}"
      SUPERSET_LOAD_EXAMPLES: "no"
    volumes:
      - superset_data:/app/superset_home

volumes:
  pg_data:
  superset_data:  