services:
  db:
    image: postgres:16
    #container_name: medical_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./backend
    container_name: fast_api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/MIS
    ports:
      - "8000:8000"

  dashboard:
    build: ./frontend
    #container_name: streamlit_ui
    depends_on:
      - api
    ports:
      - "8501:8501"
    environment:
      API_URL: http://api:8000

volumes:
  pg_data: